In [ ]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.14.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.13.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [ ]:
from imblearn.pipeline import Pipeline as ImbPipeline
from scikeras.wrappers import KerasClassifier
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.utils import resample
from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV, LearningCurveDisplay
from sklearn.svm import LinearSVC
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif, VarianceThreshold
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.tree import DecisionTreeClassifier

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Molecules_Toxicity_Classification.csv to Molecules_Toxicity_Classification.csv

In [ ]:
import io
import pandas as pd

file_path = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_path]))
df.head()

,Unnamed: 0,MATS3v,nHBint10,MATS3s,MATS3p,nHBDon_Lipinski,minHBint8,MATS3e,MATS3c,minHBint2,...,WTPT-4,WTPT-5,ETA_EtaP_L,ETA_EtaP_F,ETA_EtaP_B,nT5Ring,SHdNH,ETA_dEpsilon_C,MDEO-22,Class
0,0,0.0908,0,0.0075,0.0173,0,0.0,-0.0436,0.0409,0.0000,...,0.0000,0.0000,0.1780,1.5488,0.0088,0,0.0,-0.0868,0.00,NonToxic
1,1,0.0213,0,0.1144,-0.0410,0,0.0,0.1231,-0.0316,0.0000,...,8.8660,19.3525,0.1739,1.3718,0.0048,2,0.0,-0.0810,0.25,NonToxic
2,2,0.0018,0,-0.0156,-0.0765,2,0.0,-0.1138,-0.1791,0.0000,...,5.2267,27.8796,0.1688,1.4395,0.0116,2,0.0,-0.1004,0.00,NonToxic
3,3,-0.0251,0,-0.0064,-0.0894,3,0.0,-0.0747,-0.1151,0.0000,...,7.7896,24.7336,0.1702,1.4654,0.0133,2,0.0,-0.1010,0.00,NonToxic
4,4,-0.0028,2,-0.0164,-0.0912,2,0.0,-0.0356,-0.0159,6.0139,...,15.6022,6.2113,0.1755,1.4774,0.0133,0,0.0,-0.0980,0.00,NonToxic

In [ ]:
df.shape

(159, 1205)

In [ ]:
df.dtypes

Unnamed: 0          int64
MATS3v            float64
nHBint10            int64
MATS3s            float64
MATS3p            float64
                   ...
nT5Ring             int64
SHdNH             float64
ETA_dEpsilon_C    float64
MDEO-22           float64
Class              object
Length: 1205, dtype: object

In [ ]:
df.drop(columns=[df.columns[0]], inplace=True)

In [ ]:
label_encoder = LabelEncoder()
df['Class'] = label_encoder.fit_transform(df['Class'])  # 0: NonToxic, 1: Toxic

In [ ]:
X = df.drop(columns=['Class'])
y = df['Class']

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam, RMSprop

In [ ]:
from tensorflow.keras.optimizers import Adam, RMSprop

def create_model(learning_rate=0.001, optimizer='adam'):
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    if optimizer == 'adam':
        opt = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        opt = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Invalid optimizer")

    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['AUC'])
    return model

In [ ]:
from scikeras.wrappers import KerasClassifier

nn_clf = KerasClassifier(model=create_model, verbose=0)

In [ ]:
NN_params = {
    "classifier__model__learning_rate": [0.001, 0.0001],
    "classifier__model__optimizer": ['adam', 'rmsprop']
}

In [ ]:
from sklearn.model_selection import GridSearchCV
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.preprocessing import StandardScaler

In [ ]:
nn_clf = KerasClassifier(model=create_model, verbose=0)

NN_pipeline = ImbPipeline([
    ('scaler', StandardScaler()),
    ('classifier', nn_clf)
])

In [ ]:
cv = 5
NN_grid_search = GridSearchCV(NN_pipeline, NN_params, scoring="roc_auc", cv=cv)
NN_grid_search.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier',
                                        KerasClassifier(model=<function create_model at 0x7a2cc0e63420>, verbose=0))]),
             param_grid={'classifier__model__learning_rate': [0.001, 0.0001],
                         'classifier__model__optimizer': ['adam', 'rmsprop']},
             scoring='roc_auc')

In [ ]:
nn_best = NN_grid_search.best_estimator_
print(nn_best)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 KerasClassifier(model=<function create_model at 0x7a2cc0e63420>, model__learning_rate=0.001, model__optimizer='adam', verbose=0))])

In [ ]:
print(NN_grid_search.best_params_)

NameError: name 'NN_grid_search' is not defined

In [ ]:
best_lr = NN_grid_search.best_params_["classifier__model__learning_rate"]
best_optimizer = NN_grid_search.best_params_["classifier__model__optimizer"]
print(f"Best Learning Rate: {best_lr}")
print(f"Best Optimizer: {best_optimizer}")

Best Learning Rate: 0.001
Best Optimizer: adam

In [ ]:
NN_grid_search.fit(X_train, y_train)
nn_best = NN_grid_search.best_estimator_

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score

In [ ]:
print(NN_grid_search.best_params_)
print(NN_grid_search.best_score_)

{'classifier__model__learning_rate': 0.001, 'classifier__model__optimizer': 'adam'}
nan

In [ ]:
import numpy as np

print("Unique values in y_train:", np.unique(y_train))
print("Any NaNs in y_train:", np.isnan(y_train).any())

Unique values in y_train: [0 1]
Any NaNs in y_train: False

In [ ]:
import pandas as pd
pd.DataFrame(NN_grid_search.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier__model__learning_rate,param_classifier__model__optimizer,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,1.779067,0.177653,0.001260,0.000206,0.0010,adam,"{'classifier__model__learning_rate': 0.001, 'c...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,1.368082,0.222979,0.001166,0.000058,0.0010,rmsprop,"{'classifier__model__learning_rate': 0.001, 'c...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2.151893,0.677542,0.001601,0.000403,0.0001,adam,"{'classifier__model__learning_rate': 0.0001, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,3.112689,1.267611,0.003707,0.001469,0.0001,rmsprop,"{'classifier__model__learning_rate': 0.0001, '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [ ]:
NN_grid_search = GridSearchCV(NN_pipeline, NN_params, scoring="roc_auc", cv=3)
NN_grid_search.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
WARNING:tensorflow:5 out of the last 14 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x7a2c949db4c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
WARNING:tensorflow:5 out of the last 13 calls to <function TensorFlowTrainer._make_function.<locals>.multi_step_on_iterator at 0x7a2c94b7b6a0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 380, in _score
    y_pred = method_caller(
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 90, in _cached_call
    result, _ = _get_response_values(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/utils/_response.py", line 235, in _get_response_values
    raise ValueError(
ValueError: Pipeline should either be a classifier to be used with response_method=predict_proba or the response_method should be 'predict'. Got a regressor with response_method=predict_proba instead.

  warnings.warn(
/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py:960: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/sklearn/model_selection/_validation.py", line 949, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_scorer.py", line 288, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('classifier',
                                        KerasClassifier(model=<function create_model at 0x7a2cc0e63420>, verbose=0))]),
             param_grid={'classifier__model__learning_rate': [0.001, 0.0001],
                         'classifier__model__optimizer': ['adam', 'rmsprop']},
             scoring='roc_auc')

In [ ]:
if hasattr(nn_best, "predict_proba"):
    print("predict_proba is available")
else:
    print("predict_proba is NOT available")

predict_proba is available

In [ ]:
nn_model = nn_best.named_steps["classifier"]  # Extract the final estimator
nn_y_pred_proba = nn_model.predict_proba(X_test)  # Get probability estimates
nn_y_pred = (nn_y_pred_proba[:, 1] >= 0.6).astype(int)  # Apply threshold

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, nn_y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.7188

In [ ]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, nn_y_pred))

[[23  1]
 [ 8  0]]

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(y_test, nn_y_pred))

              precision    recall  f1-score   support

           0       0.74      0.96      0.84        24
           1       0.00      0.00      0.00         8

    accuracy                           0.72        32
   macro avg       0.37      0.48      0.42        32
weighted avg       0.56      0.72      0.63        32

In [ ]:
from sklearn.metrics import roc_auc_score

auc_score = roc_auc_score(y_test, nn_y_pred_proba[:, 1])
print(f"AUC-ROC: {auc_score:.4f}")

AUC-ROC: 0.4844


# Trial 1

In [ ]:
!pip install scikeras

from imblearn.pipeline import Pipeline as ImbPipeline
from scikeras.wrappers import KerasClassifier
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix, ConfusionMatrixDisplay
from sklearn.utils import resample
from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, GridSearchCV, LearningCurveDisplay
from sklearn.svm import LinearSVC
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_classif, VarianceThreshold
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.tree import DecisionTreeClassifier

Requirement already satisfied: scikeras in /usr/local/lib/python3.11/dist-packages (0.13.0)
Requirement already satisfied: keras>=3.2.0 in /usr/local/lib/python3.11/dist-packages (from scikeras) (3.8.0)
Requirement already satisfied: scikit-learn>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.0.8)
Requirement already satisfied: h5py in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (3.13.0)
Requirement already satisfied: optree in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.14.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (0.4.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from optree->keras>=3.2.0->scikeras) (4.13.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich->keras>=3.2.0->scikeras) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.2)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Molecules_Toxicity_Classification.csv to Molecules_Toxicity_Classification (1).csv

In [ ]:
import io
import pandas as pd

file_path = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[file_path]))
df.head()

,Unnamed: 0,MATS3v,nHBint10,MATS3s,MATS3p,nHBDon_Lipinski,minHBint8,MATS3e,MATS3c,minHBint2,...,WTPT-4,WTPT-5,ETA_EtaP_L,ETA_EtaP_F,ETA_EtaP_B,nT5Ring,SHdNH,ETA_dEpsilon_C,MDEO-22,Class
0,0,0.0908,0,0.0075,0.0173,0,0.0,-0.0436,0.0409,0.0000,...,0.0000,0.0000,0.1780,1.5488,0.0088,0,0.0,-0.0868,0.00,NonToxic
1,1,0.0213,0,0.1144,-0.0410,0,0.0,0.1231,-0.0316,0.0000,...,8.8660,19.3525,0.1739,1.3718,0.0048,2,0.0,-0.0810,0.25,NonToxic
2,2,0.0018,0,-0.0156,-0.0765,2,0.0,-0.1138,-0.1791,0.0000,...,5.2267,27.8796,0.1688,1.4395,0.0116,2,0.0,-0.1004,0.00,NonToxic
3,3,-0.0251,0,-0.0064,-0.0894,3,0.0,-0.0747,-0.1151,0.0000,...,7.7896,24.7336,0.1702,1.4654,0.0133,2,0.0,-0.1010,0.00,NonToxic
4,4,-0.0028,2,-0.0164,-0.0912,2,0.0,-0.0356,-0.0159,6.0139,...,15.6022,6.2113,0.1755,1.4774,0.0133,0,0.0,-0.0980,0.00,NonToxic

In [ ]:
df.shape

(159, 1205)

In [ ]:
df.dtypes

Unnamed: 0          int64
MATS3v            float64
nHBint10            int64
MATS3s            float64
MATS3p            float64
                   ...
nT5Ring             int64
SHdNH             float64
ETA_dEpsilon_C    float64
MDEO-22           float64
Class              object
Length: 1205, dtype: object

In [ ]:
label_encoder = LabelEncoder()
df['Class'] = label_encoder.fit_transform(df['Class'])  # 0: NonToxic, 1: Toxic

In [ ]:
X = df.drop(columns=['Class'])
y = df['Class']

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [ ]:
class_weights = compute_class_weight(class_weight="balanced", classes=np.unique(y_train), y=y_train)
class_weights_dict = {i: class_weights[i] for i in range(len(class_weights))}

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, BatchNormalization, Dropout

def create_model(learning_rate=0.001, optimizer='adam'):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.3),
        Dense(64, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    if optimizer == 'adam':
        opt = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        opt = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Invalid optimizer")

    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['AUC'])
    return model

In [ ]:
model = create_model(learning_rate=0.001, optimizer='adam')
model.fit(X_train, y_train, class_weight=class_weights_dict, epochs=20, batch_size=32)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - AUC: 0.5053 - loss: 0.8868
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.8138 - loss: 0.5078
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9044 - loss: 0.4038
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9602 - loss: 0.3301
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9378 - loss: 0.3429
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9873 - loss: 0.2528
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9865 - loss: 0.2362
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - AUC: 0.9770 - loss: 0.2477
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9868 - loss: 0.2008
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9873 - loss: 0.1869
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9941 - loss: 0.1588
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9974 - loss: 0.1475
Epoch 13/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9988 - loss: 0.1083
Epoch 14/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - AUC: 0.9994 - loss: 0.1078
Epoch 15/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 1.0000 - loss: 0.0928
Epoch 16/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9995 - loss: 0.1083
Epoch 17/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9961 - loss: 0.1093
Epoch 18/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - AUC: 0.9988 - loss: 0.0967
Epoch 19/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - AUC: 0.9991 - loss: 0.0793
Epoch 20/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - AUC: 0.9973 - loss: 0.0937


# Trial 2

In [ ]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

print("Resampled class distribution:", np.bincount(y_train_resampled))

Resampled class distribution: [84 84]

In [ ]:
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight("balanced", classes=np.unique(y_train), y=y_train)
class_weights_dict = {i: class_weights[i] for i in range(len(class_weights))}
print("Class Weights:", class_weights_dict)

Class Weights: {0: np.float64(0.7559523809523809), 1: np.float64(1.4767441860465116)}

In [ ]:
model = create_model(learning_rate=0.001, optimizer='adam')
model.fit(X_train_resampled, y_train_resampled, class_weight=class_weights_dict, epochs=20, batch_size=32)

Epoch 1/20

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

6/6 ━━━━━━━━━━━━━━━━━━━━ 4s 15ms/step - AUC: 0.5549 - loss: 1.1426
Epoch 2/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.8913 - loss: 0.4677
Epoch 3/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - AUC: 0.9280 - loss: 0.3867
Epoch 4/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9527 - loss: 0.3416
Epoch 5/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.9806 - loss: 0.2636
Epoch 6/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.9843 - loss: 0.2451
Epoch 7/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.9911 - loss: 0.1988
Epoch 8/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - AUC: 0.9830 - loss: 0.2085
Epoch 9/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9948 - loss: 0.1371
Epoch 10/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9895 - loss: 0.1722
Epoch 11/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - AUC: 0.9991 - loss: 0.1140
Epoch 12/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.9959 - loss: 0.1213
Epoch 13/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.9986 - loss: 0.1054
Epoch 14/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9992 - loss: 0.0883
Epoch 15/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9994 - loss: 0.1050
Epoch 16/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - AUC: 0.9966 - loss: 0.1083
Epoch 17/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9986 - loss: 0.0924
Epoch 18/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - AUC: 0.9966 - loss: 0.0980
Epoch 19/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - AUC: 0.9914 - loss: 0.1100
Epoch 20/20
6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - AUC: 0.9988 - loss: 0.0832

In [ ]:
def create_model(learning_rate=0.001, optimizer='adam'):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.3),
        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.3),
        Dense(32, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    if optimizer == 'adam':
        opt = Adam(learning_rate=learning_rate)
    elif optimizer == 'rmsprop':
        opt = RMSprop(learning_rate=learning_rate)
    else:
        raise ValueError("Invalid optimizer")

    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['AUC'])
    return model

In [ ]:
NN_params = {
    "classifier__model__learning_rate": [0.01, 0.001, 0.0001],
    "classifier__model__optimizer": ['adam', 'rmsprop'],
    "classifier__batch_size": [16, 32, 64],
    "classifier__epochs": [10, 20, 30]
}

In [ ]:
NN_grid_search = GridSearchCV(NN_pipeline, NN_params, scoring="f1", cv=5)

In [ ]:
nn_y_pred_proba = model.predict(X_test)
nn_y_pred = (nn_y_pred_proba >= 0.6).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, nn_y_pred)
print(f" Accuracy: {accuracy:.4f}")

 Accuracy: 0.5938

In [ ]:
from sklearn.metrics import confusion_matrix
print(" Confusion Matrix:")
print(confusion_matrix(y_test, nn_y_pred))

 Confusion Matrix:
[[18  6]
 [ 7  1]]

In [ ]:
from sklearn.metrics import classification_report
print(" Classification Report:")
print(classification_report(y_test, nn_y_pred))

 Classification Report:
              precision    recall  f1-score   support

           0       0.72      0.75      0.73        24
           1       0.14      0.12      0.13         8

    accuracy                           0.59        32
   macro avg       0.43      0.44      0.43        32
weighted avg       0.58      0.59      0.58        32

In [ ]:
from sklearn.metrics import roc_auc_score
auc_score = roc_auc_score(y_test, nn_y_pred_proba)
print(f" AUC-ROC: {auc_score:.4f}")

 AUC-ROC: 0.5885

# Trial 3

In [ ]:
nn_y_pred = (nn_y_pred_proba >= 0.5).astype(int)

In [ ]:
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

def create_model(learning_rate=0.001, optimizer='adam'):
    model = Sequential([
        Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.3),
        Dense(64, activation='relu'),
        BatchNormalization(),
        Dropout(0.3),
        Dense(1, activation='sigmoid')
    ])

    opt = Adam(learning_rate=learning_rate) if optimizer == 'adam' else RMSprop(learning_rate=learning_rate)
    model.compile(optimizer=opt, loss='binary_crossentropy', metrics=['AUC'])
    return model

In [ ]:
class_weights_dict = {0: 1, 1: 3}

In [ ]:
model = create_model(learning_rate=0.0005, optimizer='adam')
history = model.fit(X_train, y_train, epochs=50, batch_size=16, class_weight=class_weights_dict, validation_data=(X_test, y_test))

Epoch 1/50

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

8/8 ━━━━━━━━━━━━━━━━━━━━ 5s 68ms/step - AUC: 0.5960 - loss: 1.3641 - val_AUC: 0.3750 - val_loss: 0.9023
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.7399 - loss: 1.0971 - val_AUC: 0.3385 - val_loss: 0.9564
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - AUC: 0.8318 - loss: 0.8263 - val_AUC: 0.3672 - val_loss: 0.9793
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - AUC: 0.8742 - loss: 0.6987 - val_AUC: 0.3698 - val_loss: 0.9647
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - AUC: 0.8336 - loss: 0.7863 - val_AUC: 0.3802 - val_loss: 1.0051
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.8284 - loss: 0.8974 - val_AUC: 0.3958 - val_loss: 1.0081
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9612 - loss: 0.5045 - val_AUC: 0.4219 - val_loss: 0.9897
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.8572 - loss: 0.7648 - val_AUC: 0.4349 - val_loss: 0.9609
Epoch 9/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - AUC: 0.9686 - loss: 0.4564 - val_AUC: 0.4766 - val_loss: 0.9566
Epoch 10/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9471 - loss: 0.5362 - val_AUC: 0.4740 - val_loss: 0.9560
Epoch 11/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9362 - loss: 0.5093 - val_AUC: 0.4479 - val_loss: 0.9620
Epoch 12/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9688 - loss: 0.4497 - val_AUC: 0.4948 - val_loss: 0.9780
Epoch 13/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9524 - loss: 0.4845 - val_AUC: 0.4948 - val_loss: 1.0380
Epoch 14/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - AUC: 0.9588 - loss: 0.4563 - val_AUC: 0.4844 - val_loss: 1.0578
Epoch 15/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - AUC: 0.9480 - loss: 0.5183 - val_AUC: 0.4661 - val_loss: 1.0574
Epoch 16/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9761 - loss: 0.3927 - val_AUC: 0.4661 - val_loss: 1.0935
Epoch 17/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9889 - loss: 0.2936 - val_AUC: 0.4766 - val_loss: 1.1543
Epoch 18/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9697 - loss: 0.3553 - val_AUC: 0.4583 - val_loss: 1.2230
Epoch 19/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9504 - loss: 0.4667 - val_AUC: 0.4661 - val_loss: 1.1866
Epoch 20/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - AUC: 0.9896 - loss: 0.2916 - val_AUC: 0.4948 - val_loss: 1.1541
Epoch 21/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9878 - loss: 0.2895 - val_AUC: 0.5182 - val_loss: 1.1613
Epoch 22/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9733 - loss: 0.4022 - val_AUC: 0.5286 - val_loss: 1.1522
Epoch 23/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9763 - loss: 0.3577 - val_AUC: 0.5521 - val_loss: 1.1088
Epoch 24/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9766 - loss: 0.3990 - val_AUC: 0.5651 - val_loss: 1.0870
Epoch 25/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9906 - loss: 0.3426 - val_AUC: 0.5365 - val_loss: 1.1753
Epoch 26/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - AUC: 0.9894 - loss: 0.2429 - val_AUC: 0.5234 - val_loss: 1.2046
Epoch 27/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - AUC: 0.9797 - loss: 0.3231 - val_AUC: 0.5234 - val_loss: 1.1848
Epoch 28/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9938 - loss: 0.2410 - val_AUC: 0.5182 - val_loss: 1.2388
Epoch 29/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9956 - loss: 0.2638 - val_AUC: 0.5000 - val_loss: 1.2728
Epoch 30/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9986 - loss: 0.1668 - val_AUC: 0.5182 - val_loss: 1.2459
Epoch 31/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9885 - loss: 0.2660 - val_AUC: 0.5208 - val_loss: 1.2218
Epoch 32/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - AUC: 0.9877 - loss: 0.2029 - val_AUC: 0.5130 - val_loss: 1.1797
Epoch 33/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9966 - loss: 0.2243 - val_AUC: 0.5339 - val_loss: 1.1116
Epoch 34/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - AUC: 0.9961 - loss: 0.1941 - val_AUC: 0.5365 - val_loss: 1.1099
Epoch 35/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9938 - loss: 0.2230 - val_AUC: 0.5495 - val_loss: 1.1149
Epoch 36/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - AUC: 0.9977 - loss: 0.2286 - val_AUC: 0.5651 - val_loss: 1.1547
Epoch 37/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - AUC: 0.9967 - loss: 0.2399 - val_AUC: 0.5573 - val_loss: 1.2001
Epoch 38/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - AUC: 0.9965 - loss: 0.1959 - val_AUC: 0.5703 - val_loss: 1.2546
Epoch 39/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - AUC: 0.9969 - loss: 0.1683 - val_AUC: 0.5573 - val_loss: 1.2748
Epoch 40/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9978 - loss: 0.1930 - val_AUC: 0.5443 - val_loss: 1.2069
Epoch 41/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 0.9956 - loss: 0.2040 - val_AUC: 0.5885 - val_loss: 1.1410
Epoch 42/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9850 - loss: 0.3006 - val_AUC: 0.5990 - val_loss: 1.1089
Epoch 43/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9992 - loss: 0.1527 - val_AUC: 0.5990 - val_loss: 1.1673
Epoch 44/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9909 - loss: 0.2602 - val_AUC: 0.6016 - val_loss: 1.2231
Epoch 45/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - AUC: 0.9715 - loss: 0.3431 - val_AUC: 0.6276 - val_loss: 1.2041
Epoch 46/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9834 - loss: 0.2887 - val_AUC: 0.6458 - val_loss: 1.0976
Epoch 47/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9882 - loss: 0.2339 - val_AUC: 0.6562 - val_loss: 1.0674
Epoch 48/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - AUC: 0.9981 - loss: 0.1752 - val_AUC: 0.6484 - val_loss: 1.0905
Epoch 49/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9961 - loss: 0.1746 - val_AUC: 0.6380 - val_loss: 1.1002
Epoch 50/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - AUC: 0.9942 - loss: 0.2060 - val_AUC: 0.6484 - val_loss: 1.0425

In [ ]:
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

nn_y_pred_proba = model.predict(X_test)  # Get probability predictions
nn_y_pred = (nn_y_pred_proba >= 0.5).astype(int)

# Print performance metrics
print("Confusion Matrix:\n", confusion_matrix(y_test, nn_y_pred))
print("\nClassification Report:\n", classification_report(y_test, nn_y_pred))
print("\nAUC-ROC:", roc_auc_score(y_test, nn_y_pred_proba))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
Confusion Matrix:
 [[17  7]
 [ 4  4]]

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.71      0.76        24
           1       0.36      0.50      0.42         8

    accuracy                           0.66        32
   macro avg       0.59      0.60      0.59        32
weighted avg       0.70      0.66      0.67        32


AUC-ROC: 0.6458333333333333

Since recall for class 1 improved, but precision is still low, we can try lowering the threshold to 0.35 or 0.3 to capture more true positives.

In [ ]:
nn_y_pred = (nn_y_pred_proba >= 0.35).astype(int)

# Re-evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, nn_y_pred))
print("\nClassification Report:\n", classification_report(y_test, nn_y_pred))
print("\nAUC-ROC:", roc_auc_score(y_test, nn_y_pred_proba))

Confusion Matrix:
 [[17  7]
 [ 2  6]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.71      0.79        24
           1       0.46      0.75      0.57         8

    accuracy                           0.72        32
   macro avg       0.68      0.73      0.68        32
weighted avg       0.79      0.72      0.74        32


AUC-ROC: 0.6458333333333333

In [ ]:
class_weights_dict = {0: 1, 1: 4}

In [ ]:
history = model.fit(X_train, y_train, epochs=100, batch_size=32, class_weight=class_weights_dict, validation_data=(X_test, y_test))

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 230ms/step - AUC: 0.9822 - loss: 0.2510 - val_AUC: 0.6536 - val_loss: 1.0137
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 57ms/step - AUC: 0.9965 - loss: 0.1551 - val_AUC: 0.6458 - val_loss: 1.0173
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - AUC: 0.9930 - loss: 0.2550 - val_AUC: 0.6380 - val_loss: 1.1065
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - AUC: 0.9998 - loss: 0.1197 - val_AUC: 0.6380 - val_loss: 1.1573
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - AUC: 1.0000 - loss: 0.0958 - val_AUC: 0.6380 - val_loss: 1.1867
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9950 - loss: 0.1215 - val_AUC: 0.6380 - val_loss: 1.2126
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9996 - loss: 0.1253 - val_AUC: 0.6198 - val_loss: 1.2280
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - AUC: 0.9989 - loss: 0.1407 - val_AUC: 0.6146 - val_loss: 1.2123
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9998 - loss: 0.1117 - val_AUC: 0.6172 - val_loss: 1.2115
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - AUC: 1.0000 - loss: 0.1116 - val_AUC: 0.6302 - val_loss: 1.1928
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0948 - val_AUC: 0.6250 - val_loss: 1.1597
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9998 - loss: 0.1141 - val_AUC: 0.6354 - val_loss: 1.1273
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - AUC: 1.0000 - loss: 0.0981 - val_AUC: 0.6406 - val_loss: 1.1029
Epoch 14/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - AUC: 1.0000 - loss: 0.0902 - val_AUC: 0.6458 - val_loss: 1.0911
Epoch 15/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - AUC: 1.0000 - loss: 0.0728 - val_AUC: 0.6458 - val_loss: 1.0889
Epoch 16/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - AUC: 1.0000 - loss: 0.1131 - val_AUC: 0.6432 - val_loss: 1.0954
Epoch 17/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - AUC: 0.9985 - loss: 0.1119 - val_AUC: 0.6380 - val_loss: 1.1141
Epoch 18/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - AUC: 1.0000 - loss: 0.0583 - val_AUC: 0.6328 - val_loss: 1.1167
Epoch 19/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - AUC: 0.9988 - loss: 0.1110 - val_AUC: 0.6328 - val_loss: 1.1291
Epoch 20/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - AUC: 0.9977 - loss: 0.1689 - val_AUC: 0.6276 - val_loss: 1.1746
Epoch 21/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - AUC: 0.9984 - loss: 0.1080 - val_AUC: 0.6198 - val_loss: 1.2244
Epoch 22/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - AUC: 1.0000 - loss: 0.1407 - val_AUC: 0.6224 - val_loss: 1.2194
Epoch 23/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - AUC: 1.0000 - loss: 0.0707 - val_AUC: 0.6328 - val_loss: 1.1931
Epoch 24/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - AUC: 1.0000 - loss: 0.0775 - val_AUC: 0.6224 - val_loss: 1.1813
Epoch 25/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0595 - val_AUC: 0.6198 - val_loss: 1.1848
Epoch 26/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9988 - loss: 0.1391 - val_AUC: 0.6224 - val_loss: 1.1645
Epoch 27/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9995 - loss: 0.0958 - val_AUC: 0.6432 - val_loss: 1.1537
Epoch 28/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9996 - loss: 0.0899 - val_AUC: 0.6484 - val_loss: 1.1413
Epoch 29/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0705 - val_AUC: 0.6693 - val_loss: 1.1232
Epoch 30/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - AUC: 1.0000 - loss: 0.0633 - val_AUC: 0.6693 - val_loss: 1.1175
Epoch 31/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9996 - loss: 0.0898 - val_AUC: 0.6745 - val_loss: 1.1157
Epoch 32/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0798 - val_AUC: 0.6510 - val_loss: 1.1543
Epoch 33/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - AUC: 0.9974 - loss: 0.1233 - val_AUC: 0.6432 - val_loss: 1.2041
Epoch 34/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0754 - val_AUC: 0.6536 - val_loss: 1.2695
Epoch 35/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0565 - val_AUC: 0.6536 - val_loss: 1.2928
Epoch 36/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - AUC: 0.9996 - loss: 0.0921 - val_AUC: 0.6484 - val_loss: 1.2824
Epoch 37/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - AUC: 0.9996 - loss: 0.0773 - val_AUC: 0.6562 - val_loss: 1.2365
Epoch 38/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0480 - val_AUC: 0.6667 - val_loss: 1.1488
Epoch 39/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - AUC: 1.0000 - loss: 0.0471 - val_AUC: 0.6719 - val_loss: 1.0839
Epoch 40/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0850 - val_AUC: 0.6667 - val_loss: 1.0733
Epoch 41/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9998 - loss: 0.0839 - val_AUC: 0.6641 - val_loss: 1.0982
Epoch 42/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9996 - loss: 0.0700 - val_AUC: 0.6589 - val_loss: 1.1508
Epoch 43/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9999 - loss: 0.0587 - val_AUC: 0.6615 - val_loss: 1.2160
Epoch 44/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0732 - val_AUC: 0.6536 - val_loss: 1.2070
Epoch 45/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0572 - val_AUC: 0.6536 - val_loss: 1.1956
Epoch 46/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9989 - loss: 0.0869 - val_AUC: 0.6510 - val_loss: 1.1858
Epoch 47/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - AUC: 1.0000 - loss: 0.0466 - val_AUC: 0.6432 - val_loss: 1.1920
Epoch 48/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0443 - val_AUC: 0.6302 - val_loss: 1.2061
Epoch 49/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0465 - val_AUC: 0.6172 - val_loss: 1.2031
Epoch 50/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0450 - val_AUC: 0.6224 - val_loss: 1.1966
Epoch 51/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - AUC: 1.0000 - loss: 0.0461 - val_AUC: 0.6406 - val_loss: 1.1849
Epoch 52/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - AUC: 1.0000 - loss: 0.0394 - val_AUC: 0.6589 - val_loss: 1.1787
Epoch 53/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - AUC: 1.0000 - loss: 0.0436 - val_AUC: 0.6432 - val_loss: 1.1901
Epoch 54/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 1.0000 - loss: 0.0371 - val_AUC: 0.6458 - val_loss: 1.1903
Epoch 55/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 1.0000 - loss: 0.0383 - val_AUC: 0.6562 - val_loss: 1.1672
Epoch 56/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0393 - val_AUC: 0.6562 - val_loss: 1.1586
Epoch 57/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 0.9998 - loss: 0.0843 - val_AUC: 0.6563 - val_loss: 1.1984
Epoch 58/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 1.0000 - loss: 0.0348 - val_AUC: 0.6589 - val_loss: 1.2670
Epoch 59/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - AUC: 1.0000 - loss: 0.0521 - val_AUC: 0.6589 - val_loss: 1.3080
Epoch 60/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0482 - val_AUC: 0.6589 - val_loss: 1.3302
Epoch 61/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0462 - val_AUC: 0.6536 - val_loss: 1.3508
Epoch 62/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0243 - val_AUC: 0.6458 - val_loss: 1.3391
Epoch 63/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - AUC: 0.9987 - loss: 0.0923 - val_AUC: 0.6354 - val_loss: 1.2905
Epoch 64/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - AUC: 0.9997 - loss: 0.0812 - val_AUC: 0.6354 - val_loss: 1.2536
Epoch 65/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - AUC: 1.0000 - loss: 0.0489 - val_AUC: 0.6380 - val_loss: 1.2211
Epoch 66/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0324 - val_AUC: 0.6406 - val_loss: 1.1980
Epoch 67/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0480 - val_AUC: 0.6458 - val_loss: 1.1870
Epoch 68/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0345 - val_AUC: 0.6432 - val_loss: 1.1964
Epoch 69/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - AUC: 1.0000 - loss: 0.0436 - val_AUC: 0.6484 - val_loss: 1.1860
Epoch 70/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 1.0000 - loss: 0.0487 - val_AUC: 0.6589 - val_loss: 1.1791
Epoch 71/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0383 - val_AUC: 0.6641 - val_loss: 1.1690
Epoch 72/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0343 - val_AUC: 0.6693 - val_loss: 1.1557
Epoch 73/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - AUC: 1.0000 - loss: 0.0358 - val_AUC: 0.6693 - val_loss: 1.1526
Epoch 74/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 0.9999 - loss: 0.0667 - val_AUC: 0.6771 - val_loss: 1.1450
Epoch 75/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0657 - val_AUC: 0.6901 - val_loss: 1.1093
Epoch 76/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0481 - val_AUC: 0.6849 - val_loss: 1.1018
Epoch 77/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0390 - val_AUC: 0.6719 - val_loss: 1.1391
Epoch 78/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 0.9998 - loss: 0.0491 - val_AUC: 0.6719 - val_loss: 1.1600
Epoch 79/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - AUC: 1.0000 - loss: 0.0529 - val_AUC: 0.6797 - val_loss: 1.1424
Epoch 80/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - AUC: 1.0000 - loss: 0.0592 - val_AUC: 0.6745 - val_loss: 1.1281
Epoch 81/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - AUC: 1.0000 - loss: 0.0305 - val_AUC: 0.6693 - val_loss: 1.0920
Epoch 82/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 1.0000 - loss: 0.0434 - val_AUC: 0.6667 - val_loss: 1.0658
Epoch 83/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - AUC: 1.0000 - loss: 0.0373 - val_AUC: 0.6641 - val_loss: 1.0417
Epoch 84/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - AUC: 1.0000 - loss: 0.0272 - val_AUC: 0.6589 - val_loss: 1.0333
Epoch 85/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - AUC: 1.0000 - loss: 0.0370 - val_AUC: 0.6823 - val_loss: 1.0302
Epoch 86/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - AUC: 0.9994 - loss: 0.0825 - val_AUC: 0.6693 - val_loss: 1.0717
Epoch 87/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - AUC: 1.0000 - loss: 0.0350 - val_AUC: 0.6484 - val_loss: 1.1189
Epoch 88/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - AUC: 1.0000 - loss: 0.0458 - val_AUC: 0.6380 - val_loss: 1.1406
Epoch 89/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - AUC: 1.0000 - loss: 0.0370 - val_AUC: 0.6328 - val_loss: 1.1501
Epoch 90/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - AUC: 1.0000 - loss: 0.0324 - val_AUC: 0.6406 - val_loss: 1.1416
Epoch 91/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - AUC: 1.0000 - loss: 0.0499 - val_AUC: 0.6536 - val_loss: 1.0896
Epoch 92/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - AUC: 1.0000 - loss: 0.0172 - val_AUC: 0.6589 - val_loss: 1.0328
Epoch 93/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - AUC: 1.0000 - loss: 0.0348 - val_AUC: 0.6589 - val_loss: 1.0173
Epoch 94/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - AUC: 1.0000 - loss: 0.0619 - val_AUC: 0.6510 - val_loss: 1.0072
Epoch 95/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - AUC: 1.0000 - loss: 0.0308 - val_AUC: 0.6432 - val_loss: 1.0235
Epoch 96/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - AUC: 0.9993 - loss: 0.0841 - val_AUC: 0.6406 - val_loss: 1.0491
Epoch 97/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - AUC: 1.0000 - loss: 0.0230 - val_AUC: 0.6406 - val_loss: 1.0755
Epoch 98/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - AUC: 1.0000 - loss: 0.0266 - val_AUC: 0.6380 - val_loss: 1.1045
Epoch 99/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - AUC: 1.0000 - loss: 0.0243 - val_AUC: 0.6432 - val_loss: 1.1117
Epoch 100/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - AUC: 1.0000 - loss: 0.0363 - val_AUC: 0.6432 - val_loss: 1.1252

In [ ]:
nn_y_pred_proba = nn_best.named_steps["classifier"].predict_proba(X_test)
nn_y_pred = (nn_y_pred_proba[:, 1] >= 0.5).astype(int)  # Change threshold if needed

ValueError: X has shape (1204,), but this KerasClassifier is expecting X of shape (1203,)

In [ ]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (127, 1204)
X_test shape: (32, 1204)

In [ ]:
print("Expected input shape:", nn_best.named_steps["classifier"].model_.input_shape)

Expected input shape: (None, 1203)

In [ ]:
X_train = X_train[:, :1203]  # Keep only the first 1203 features
X_test = X_test[:, :1203]

In [ ]:
import numpy as np

X_train = np.array(X_train)
X_test = np.array(X_test)

X_train = X_train.reshape(-1, 1203)  # Ensure shape is (num_samples, num_features)
X_test = X_test.reshape(-1, 1203)

In [ ]:
nn_y_pred_proba = nn_best.named_steps["classifier"].predict_proba(X_test)
nn_y_pred = (nn_y_pred_proba[:, 1] >= 0.5).astype(int)

In [ ]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, nn_y_pred)
print(f"Accuracy: {accuracy:.4f}")

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, nn_y_pred)
print("Confusion Matrix:\n", cm)

from sklearn.metrics import classification_report

print("Classification Report:\n", classification_report(y_test, nn_y_pred))

from sklearn.metrics import roc_auc_score

auc_score = roc_auc_score(y_test, nn_y_pred_proba[:, 1])
print(f"AUC-ROC: {auc_score:.4f}")

Accuracy: 0.5625
Confusion Matrix:
 [[18  6]
 [ 8  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.69      0.75      0.72        24
           1       0.00      0.00      0.00         8

    accuracy                           0.56        32
   macro avg       0.35      0.38      0.36        32
weighted avg       0.52      0.56      0.54        32

AUC-ROC: 0.4688